###############################################
# Webhook secrets (EXAMPLE)
#
# Copy this file to config/webhook_secrets.yaml and fill in values.
# Never commit the filled-in file.
###############################################

# HMAC secret used to sign outgoing webhooks
hmac_secret: "change-me-in-prod"

